config/routes.rb
Rails.application.routes.draw do
  resources :kanjis

  get '/kj/search' => 'kanjis#search'
  get '/kj/search_form' => 'kanjis#search_form'
  
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :kanjis do
  post 'tweet', on: :collection
end

end

app/models/kanji.rb
class Kanji < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # def self.create_from_auth!(auth)
  #   create! do |user|
  #     user.provider = auth[:provider]
  #     user.uid = auth[:uid]
  #     user.name = auth[:info][:name]
  #     user.image = auth[:info][:image]
  #     user.token = auth[:credentials][:token]
  #     user.secret = auth[:credentials][:secret]
  #   end
  # end
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth[:provider]
      user.uid = auth[:uid]
      user.name = auth[:info][:name]
      user.image = auth[:info][:image]
      user.token = auth[:credentials][:token]
      user.secret = auth[:credentials][:secret]
    end
  end
  def twitter_client
  @twitter_client ||= Twitter::REST::Client.new(
  	consumer_key:        'mVYyeyXFydBtisgTKHxoJThjw',
    consumer_secret:     'IyJXS9i1YAuyMyM4gdvFmANgblkI9StLRgVMTJ2rBNifrzPj10',
    access_token:        token,
    access_token_secret: secret
  
  #config.access_token = '4900130930-vueew83PEBUCxAeHKVQweNEdlsuNPhREtY0iayn'
  #config.access_token_secret = 'yltHgujLTP5uroivixElIsriX4oKiNBYjfQN4t1CRW5ER'
  )
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 	# Prevent CSRF attacks by raising an exception.
  	# For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception

	def current_user  
    	@current_user ||= User.find(session[:user_id]) if session[:user_id]  
	end
	def twitter_client
    	twitter_client = Twitter::REST::Client.new do |config|
			config.consumer_key        = "mVYyeyXFydBtisgTKHxoJThjw"
      		config.consumer_secret     = "IyJXS9i1YAuyMyM4gdvFmANgblkI9StLRgVMTJ2rBNifrzPj10"
      		config.access_token        = "4900130930-vueew83PEBUCxAeHKVQweNEdlsuNPhREtY0iayn"
      		config.access_token_secret = "yltHgujLTP5uroivixElIsriX4oKiNBYjfQN4t1CRW5ER"
		end
    	@name = params[:name]
		user = twitter_client.user_search(@name).first
		if user
	  @user.provider = user.nproviderame
      @user.uid = user.uid
      @user.name = user.name
      @user.image = user.image
      @user.token = user.token
      @user.secret = user.secret
    else
  	end
	end
	
 	helper_method :current_user
 	helper_method :twitter_client
end

app/controllers/base_controller.rb
class BaseController < ActionController::Base
  protect_from_forgery

  def login_required
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      redirect_to root_path
    end

  end

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/kanjis_controller.rb
class KanjisController < ApplicationController
  before_action :set_kanji, only: [:show, :edit, :update, :destroy]

  # GET /kanjis
  # GET /kanjis.json
  def index
    @kanjis = Kanji.all
  end

  # GET /kanjis/1
  # GET /kanjis/1.json
  def show
  end

  # GET /kanjis/new
  def new
    @kanji = Kanji.new
  end

  # GET /kanjis/1/edit
  def edit
  end

  # POST /kanjis
  # POST /kanjis.json
  def create
    @kanji = Kanji.new(kanji_params)

    respond_to do |format|
      if @kanji.save
        format.html { redirect_to @kanji, notice: 'Kanji was successfully created.' }
        format.json { render :show, status: :created, location: @kanji }
      else
        format.html { render :new }
        format.json { render json: @kanji.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kanjis/1
  # PATCH/PUT /kanjis/1.json
  def update
    respond_to do |format|
      if @kanji.update(kanji_params)
        format.html { redirect_to @kanji, notice: 'Kanji was successfully updated.' }
        format.json { render :show, status: :ok, location: @kanji }
      else
        format.html { render :edit }
        format.json { render json: @kanji.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kanjis/1
  # DELETE /kanjis/1.json
  def destroy
    @kanji.destroy
    respond_to do |format|
      format.html { redirect_to kanjis_url, notice: 'Kanji was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @kanjis = Kanji.where("kanji = ? and yomi = ?", params[:kanji], params[:yomi])

    @message = "辞書に乗っていない読み方です!"
    if @kanjis.length > 0
       @message = "辞書に乗っている読み方です!"
    end
  end
  def search_form
    
  end

  def tweet

    current_user.twitter_client.update(params[:text])
    redirect_to "http://localhost:3000/kj/search_form", notice: 'Tweeted!'
  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kanji
      @kanji = Kanji.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kanji_params
      params.require(:kanji).permit(:kanji, :kakusu, :yomi)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(provider: auth[:provider], uid: auth[:uid]) || User.create_from_auth!(auth)
    session[:user_id] = user.id
    redirect_to '/', notice: 'sign in!'
  end
	def callback
    auth = request.env['omniauth.auth']
    user = User.find_by_provider_and_uid(auth['provider'], auth['uid']) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
  private

  def auth
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kanjis_helper.rb
module KanjisHelper
end

app/views/kanjis/_form.html.erb
<%= form_for(@kanji) do |f| %>
  <% if @kanji.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kanji.errors.count, "error") %> prohibited this kanji from being saved:</h2>

      <ul>
      <% @kanji.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kanji %><br>
    <%= f.text_field :kanji %>
  </div>
  <div class="field">
    <%= f.label :kakusu %><br>
    <%= f.number_field :kakusu %>
  </div>
  <div class="field">
    <%= f.label :yomi %><br>
    <%= f.text_field :yomi %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kanjis/edit.html.erb
<h1>Editing Kanji</h1>

<%= render 'form' %>

<%= link_to 'Show', @kanji %> |
<%= link_to 'Back', kanjis_path %>

app/views/kanjis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kanjis</h1>

<table>
  <thead>
    <tr>
      <th>Kanji</th>
      <th>Kakusu</th>
      <th>Yomi</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kanjis.each do |kanji| %>
      <tr>
        <td><%= kanji.kanji %></td>
        <td><%= kanji.kakusu %></td>
        <td><%= kanji.yomi %></td>
        <td><%= link_to 'Show', kanji %></td>
        <td><%= link_to 'Edit', edit_kanji_path(kanji) %></td>
        <td><%= link_to 'Destroy', kanji, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kanji', new_kanji_path %>

app/views/kanjis/new.html.erb
<h1>New Kanji</h1>

<%= render 'form' %>

<%= link_to 'Back', kanjis_path %>

app/views/kanjis/search.html.erb
<body style="background-color :#FFEFD5">
<div style="text-align: center; margin-top: 80px;font-size: 300%; font-family: HG創英角ﾎﾟｯﾌﾟ体">
<%= @message %>
</div>

<br>
<div style="text-align: center; margin-top: 80px;font-size: 200%; font-family: HG創英角ﾎﾟｯﾌﾟ体">
<a href="http://twitter.com/kira_appli">皆の意見を見てみよう</a>
</div>
<div style="text-align: center; margin-top: 80px;font-size: 150%; font-family: HG創英角ﾎﾟｯﾌﾟ体">
<%= link_to "Twitter ログイン", "/kj/search_form" %>
</div>
<div style="text-align: center; margin-top: 50px">
<%= button_to 'つぶやきたい！', { action: :tweet, params: { text: 'テスト' } }, id: 'button' %>
</div>
</body>

app/views/kanjis/search_form.html.erb
<body style="background-color :#FFEFD5">
<%= stylesheet_link_tag "application", :media => "all" %>
<div style="text-align: center; margin-top: 60px">
<h1 style="font-size: 400%; font-family: HG創英角ﾎﾟｯﾌﾟ体">キラキラネームですか？</h1>
</div>
<div style="text-align: center; margin-top: 60px">
<%= form_tag('/kj/search', :method => :get) do %>
  <p style="font-size: 180%; font-family: HG創英角ﾎﾟｯﾌﾟ体">
  名前を入力してください： <%= text_field_tag 'kanji' %></p>
  <br>
  <p style="font-size: 180%; font-family: HG創英角ﾎﾟｯﾌﾟ体">
  名前の読み方を入力してください： <%= text_field_tag 'yomi' %>
  </p>
  <%= button_tag '判定', id: 'button' %>
<% end %>
<a class="twitter-timeline" href="https://twitter.com/kira_appli" data-widget-id="698487438524583937">@kira_appliさんのツイート</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id))
{js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}
(document,"script","twitter-wjs");</script>
</div>

<% if current_user %>
  <%= current_user.name %>

  <% end %>

</body>

app/views/kanjis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kanji:</strong>
  <%= @kanji.kanji %>
</p>

<p>
  <strong>Kakusu:</strong>
  <%= @kanji.kakusu %>
</p>

<p>
  <strong>Yomi:</strong>
  <%= @kanji.yomi %>
</p>

<%= link_to 'Edit', edit_kanji_path(@kanji) %> |
<%= link_to 'Back', kanjis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>